- hosts: node
  become: yes
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  tasks:
    - name: start service node, if stopped
      service:
        name: node
        state: started
